#!/usr/bin/env node

/**
 * Автоматический скрипт настройки Polygon Arbitrage Bot
 * Запуск: node setup.js
 */

const fs = require('fs-extra');
const path = require('path');
const readline = require('readline');

class BotSetup {
    constructor() {
        this.rl = readline.createInterface({
            input: process.stdin,
            output: process.stdout
        });
    }
    
    async run() {
        console.log('🚀 Polygon Arbitrage Bot Setup');
        console.log('═'.repeat(50));
        
        try {
            await this.createDirectories();
            await this.setupEnvironment();
            await this.validateSetup();
            
            console.log('\n✅ Setup completed successfully!');
            console.log('\n📋 Next steps:');
            console.log('1. Review your .env file');
            console.log('2. Run: npm start');
            console.log('3. Monitor logs for any issues');
            
        } catch (error) {
            console.error('\n❌ Setup failed:', error.message);
            process.exit(1);
        } finally {
            this.rl.close();
        }
    }
    
    async createDirectories() {
        console.log('\n📁 Creating directory structure...');
        
        const directories = [
            './data',
            './logs',
            './cache',
            './config',
            './scripts',
            './test'
        ];
        
        for (const dir of directories) {
            await fs.ensureDir(dir);
            console.log(`  ✅ ${dir}`);
        }
    }
    
    async setupEnvironment() {
        console.log('\n⚙️ Setting up environment configuration...');
        
        const envPath = './.env';
        const envExamplePath = './.env.example';
        
        // Создаем .env.example если его нет
        if (!await fs.pathExists(envExamplePath)) {
            const envExample = this.getEnvExample();
            await fs.writeFile(envExamplePath, envExample);
            console.log('  ✅ Created .env.example');
        }
        
        // Проверяем существующий .env
        if (await fs.pathExists(envPath)) {
            const answer = await this.askQuestion('  .env file already exists. Overwrite? (y/N): ');
            if (answer.toLowerCase() !== 'y') {
                console.log('  ⏭️ Skipping .env creation');
                return;
            }
        }
        
        // Интерактивная настройка .env
        const config = await this.collectConfiguration();
        const envContent = this.generateEnvContent(config);
        
        await fs.writeFile(envPath, envContent);
        console.log('  ✅ Created .env file');
    }
    
    async collectConfiguration() {
        console.log('\n📝 Configuration setup (press Enter to skip optional fields):');
        
        const config = {};
        
        // RPC Provider
        console.log('\n🌐 RPC Provider (choose one):');
        config.alchemyKey = await this.askQuestion('  Alchemy API Key (recommended): ');
        
        if (!config.alchemyKey) {
            config.infuraKey = await this.askQuestion('  Infura API Key (alternative): ');
        }
        
        if (!config.alchemyKey && !config.infuraKey) {
            config.customRpc = await this.askQuestion('  Custom RPC URL: ');
        }
        
        // Telegram
        console.log('\n📱 Telegram Notifications (optional but recommended):');
        config.telegramToken = await this.askQuestion('  Telegram Bot Token: ');
        if (config.telegramToken) {
            config.telegramChatId = await this.askQuestion('  Telegram Chat ID: ');
        }
        
        // Trading Parameters
        console.log('\n💰 Trading Parameters:');
        config.minBasisPoints = await this.askQuestion('  Minimum spread (basis points, default 50): ') || '50';
        config.inputAmount = await this.askQuestion('  Trade size USD (default 1000): ') || '1000';
        config.checkInterval = await this.askQuestion('  Check interval seconds (default 15): ') || '15';
        
        return config;
    }
    
    generateEnvContent(config) {
        let content = '# Polygon Arbitrage Bot Configuration\n';
        content += '# Generated by setup script\n\n';
        
        // RPC Providers
        content += '# ===================================\n';
        content += '# RPC PROVIDERS\n';
        content += '# ===================================\n';
        
        if (config.alchemyKey) {
            content += `ALCHEMY_API_KEY=${config.alchemyKey}\n`;
        } else {
            content += '#ALCHEMY_API_KEY=your_alchemy_api_key_here\n';
        }
        
        if (config.infuraKey) {
            content += `INFURA_API_KEY=${config.infuraKey}\n`;
        } else {
            content += '#INFURA_API_KEY=your_infura_api_key_here\n';
        }
        
        if (config.customRpc) {
            content += `POLYGON_RPC_1=${config.customRpc}\n`;
        } else {
            content += '#POLYGON_RPC_1=https://polygon-rpc.com\n';
        }
        
        content += '\n';
        
        // Telegram
        content += '# ===================================\n';
        content += '# TELEGRAM NOTIFICATIONS\n';
        content += '# ===================================\n';
        
        if (config.telegramToken) {
            content += `TELEGRAM_BOT_TOKEN=${config.telegramToken}\n`;
        } else {
            content += '#TELEGRAM_BOT_TOKEN=your_telegram_bot_token_here\n';
        }
        
        if (config.telegramChatId) {
            content += `TELEGRAM_CHAT_ID=${config.telegramChatId}\n`;
        } else {
            content += '#TELEGRAM_CHAT_ID=your_telegram_chat_id_here\n';
        }
        
        content += '\n';
        
        // Trading Parameters
        content += '# ===================================\n';
        content += '# TRADING PARAMETERS\n';
        content += '# ===================================\n';
        content += `MIN_BASIS_POINTS=${config.minBasisPoints}\n`;
        content += `INPUT_AMOUNT_USD=${config.inputAmount}\n`;
        content += `CHECK_INTERVAL_MS=${parseInt(config.checkInterval) * 1000}\n`;
        
        return content;
    }
    
    async validateSetup() {
        console.log('\n🔍 Validating setup...');
        
        // Проверка package.json
        if (!await fs.pathExists('./package.json')) {
            console.log('  ⚠️ Warning: package.json not found');
        } else {
            console.log('  ✅ package.json exists');
        }
        
        // Проверка основных файлов
        const requiredFiles = [
            './scripts/arbitrageBot.js',
            './scripts/priceFetcher.js',
            './scripts/logger.js',
            './config/polygon.json'
        ];
        
        for (const file of requiredFiles) {
            if (await fs.pathExists(file)) {
                console.log(`  ✅ ${file}`);
            } else {
                console.log(`  ❌ Missing: ${file}`);
            }
        }
        
        // Проверка .env
        if (await fs.pathExists('./.env')) {
            console.log('  ✅ .env file created');
            
            // Простая валидация .env
            const envContent = await fs.readFile('./.env', 'utf-8');
            if (envContent.includes('ALCHEMY_API_KEY=') || 
                envContent.includes('INFURA_API_KEY=') || 
                envContent.includes('POLYGON_RPC_1=')) {
                console.log('  ✅ RPC provider configured');
            } else {
                console.log('  ⚠️ Warning: No RPC provider configured');
            }
        }
    }
    
    askQuestion(question) {
        return new Promise(resolve => {
            this.rl.question(question, answer => {
                resolve(answer.trim());
            });
        });
    }
    
    getEnvExample() {
        return `# Polygon Arbitrage Bot Environment Configuration
# Copy this file to .env and fill in your values

# ===================================
# RPC PROVIDERS (At least one required)
# ===================================
ALCHEMY_API_KEY=your_alchemy_api_key_here
#INFURA_API_KEY=your_infura_api_key_here
#POLYGON_RPC_1=https://polygon-rpc.com

# ===================================
# TELEGRAM NOTIFICATIONS (Optional)
# ===================================
#TELEGRAM_BOT_TOKEN=your_telegram_bot_token_here
#TELEGRAM_CHAT_ID=your_telegram_chat_id_here

# ===================================
# TRADING PARAMETERS
# ===================================
MIN_BASIS_POINTS=50
INPUT_AMOUNT_USD=1000
CHECK_INTERVAL_MS=15000
`;
    }
}

// Запуск setup
if (require.main === module) {
    const setup = new BotSetup();
    setup.run().catch(console.error);
}

module.exports = BotSetup;